name = "BTree"
uuid = "7f6fcbf7-db5b-4c91-bcc8-2271d78944e8"
authors = ["Matthew Griffiths"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
